### ISSUE TITLE
peer-to-peer code reviews Choice-Tracy-Recillah-Eva

### ISSUE THREAD

**Issue by Recillah-Khamala** [BucurEva87/Portfolio#16]
Your project looks good.
It follows the set instructions.
I love the animations included.
You have done a good job.

Suggestions
Kindly ensure that the navbar remains on the top menu when scrolling through the project.

**Comment by techEmprez** [comment]
### **Hey There! 👋🏽** 
### Awesome Job... Beautiful Replication!!! 😄 

Just a little fixing to be done:

- The project section has some missing images when compared to the figma file 
  Just add them and we're done.

### **_Gracais and Weldone!!! 🤝_**

**Comment by elfin-git** [comment]
**Acknowledgements**
-The project is beautifully done! I love the animation of the "see project" container and its buttons. 
**Suggested Changes**
-Please adjust the position of exit button on the modal popup, It is a bit higher on some screen resolutions
-Your mobile menu popup seems to appear whenever I click on a page link on the desktop version, please take a look at that.

**Comment by BucurEva87** [comment]
Fixed.
